// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SocialLifeContext))]
    [Migration("20230922170814_added initial values")]
    partial class addedinitialvalues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.entities.Mobile", b =>
                {
                    b.Property<string>("mobile_number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Personcustom_id")
                        .HasColumnType("int");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mobile_number");

                    b.HasIndex("Personcustom_id");

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("DAL.entities.Person", b =>
                {
                    b.Property<int>("custom_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("custom_id"));

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile_number")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("custom_id");

                    b.HasIndex("mobile_number");

                    b.ToTable("people");
                });

            modelBuilder.Entity("DAL.entities.Mobile", b =>
                {
                    b.HasOne("DAL.entities.Person", null)
                        .WithMany()
                        .HasForeignKey("Personcustom_id");
                });

            modelBuilder.Entity("DAL.entities.Person", b =>
                {
                    b.HasOne("DAL.entities.Mobile", null)
                        .WithMany()
                        .HasForeignKey("mobile_number");
                });
#pragma warning restore 612, 618
        }
    }
}
